"""0.13 task acceptance through real native dialogs, mouse/keys and ngspice."""
import argparse,json,os,sys,time,traceback
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path[:0]=[str(ROOT),str(ROOT/'tests')];a=argparse.ArgumentParser();a.add_argument('--output',required=True);a.add_argument('--ngspice');args=a.parse_args();out=Path(args.output).resolve();out.mkdir(parents=True,exist_ok=True);os.environ['XDG_CONFIG_HOME']=str(out/'profile/config');os.environ['XDG_DATA_HOME']=str(out/'profile/data')
from PySide6.QtWidgets import QApplication,QDialogButtonBox
from PySide6.QtCore import Qt,QPointF
from PySide6.QtTest import QTest
from icstudio.gui import Studio
from icstudio.model import clone,digest,save_project,load_project,device,validate
from icstudio import capture_ops as ops,electrical_rules,cross_probe
from icstudio.symbol_geometry import enriched
from test_consistency import fixture,rename
errors=[];sys.excepthook=lambda t,v,tb:(errors.append(str(v)),traceback.print_exception(t,v,tb));app=QApplication([]);app.setStyle('Fusion');w=Studio(recover=False);w.error=lambda e:errors.append(str(e));w.resize(1520,980);w.show();w.activateWindow();checks=[]
p,root,cid,did=fixture();w.set_project(p);w.cid=root;w.refresh(True);before=clone(w.project);w.select([did]);w.capture_enter(True);editor=w._symbol_dialog;s=rename(editor.pad.symbol,'vin','input');s['pins']['sense']=[100,100];s['pin_order'].append('sense');s=enriched(s);s['pin_meta']['input']['direction']='in';editor.pad.apply(s);editor.save();review=w._interface_review;QTest.qWait(50);assert not editor.saved and review.isVisible();assert w.project['cells']==before['cells'];assert review.apply_button.isEnabled(),review.error.text()
for i in range(review.connections.rowCount()):review.connections.item(i,2).setText('out')
assert not review.apply_button.isEnabled();review.prepare();assert review.apply_button.isEnabled(),review.error.text();review.grab().save(str(out/'interface-review.png'));review.apply_button.click();assert editor.saved;assert ops.cell(w.project,cid)['ports'][-1]=='sense';inst=next(d for d in w.cell['devices'] if d['id']==did);assert inst['nets']['input']=='vin' and inst['nets']['sense']=='out';checks.append('native interface review maps rename and added connection, exposes missing physical port, and commits every view together')
after=clone(w.project);w.undo();assert w.project['cells']==before['cells'];w.redo();assert w.project['cells']==after['cells'];checks.append('one Undo and one Redo restore the complete multi-view change')
w.check('erc');missing=next(i for i,r in enumerate(w.issues) if r['code']=='LAYOUT.PORTS' and r['pin']=='sense');w.check_selected(missing,0);assert w.cid==cid and w._capture_stack[-1][1]==[did] and w.current_mode=='layout';checks.append('electrical finding enters the precise hierarchy occurrence and opens its physical view')
# Resolve the added sense terminal inside the amplifier and assign its physical port.
def finish(p):
    c=ops.cell(p,cid);d=device('R','RSENSE',300,100,value='1G',nets={'p':'sense','n':'0'});d['net_labels']=clone(d['nets']);c['devices'].append(d);c['layout_ports'].append({'name':'sense','layer':'metal1','point':[6000,0]})
    from icstudio.layout import rect
    c['shapes'].append(rect('metal1',5900,-100,200,200,net='sense'))
w.capture_commit(finish,'Connect sense port and assign layout terminal');w.capture_leave();w.check('erc');assert not w.issues,w.issues;checks.append('resolve interface findings with an internal sense load and explicit physical port')
w.electrical_policy_dialog();policy=w._electrical_policy;policy.fields['ERC.DANGLING'].setCurrentText('error');policy.scope.setCurrentIndex(1);policy.findChild(QDialogButtonBox).button(QDialogButtonBox.Save).click();assert w.project['electrical_rules']['rules']['ERC.DANGLING']=='error';checks.append('native electrical rule policy applies to project checks and is undoable')
w.open_cross_probe();probe=w._cross_probe;row=next(i for i,r in enumerate(probe.state['rows']) if r['object']==did);probe.table.selectRow(row);probe.act('layout');assert w.cid==root and w.current_mode=='layout' and ops.cell(w.project,root)['layout_instances'][0]['id'] in w.layout.selection;probe.mode.setCurrentIndex(1);probe.net.setCurrentText('vin');row=next(i for i,r in enumerate(probe.state['rows']) if r['cell']==cid);probe.table.selectRow(row);probe.act('schematic');assert w.cid==cid and w.net=='input' and w._capture_stack[-1][1]==[did];probe.grab().save(str(out/'cross-probe.png'));probe.close();w.capture_leave();checks.append('linked placement selection and renamed net propagation across the hierarchy')
path=out/'amplifier-interface-update.icproj';save_project(w.project,path);q=load_project(path);assert q['cells']==w.project['cells'] and q['electrical_rules']==w.project['electrical_rules'];w.set_project(q,path);w.cid=root;w.refresh(True);checks.append('saved bench, interface history, physical ports and rule policy survive reopening')
if args.ngspice:
    w.settings.setValue('engine/ngspice',str(Path(args.ngspice).resolve()));w.run_testbench();deadline=time.monotonic()+45
    while w.process and time.monotonic()<deadline:QTest.qWait(20)
    assert not w.process and w._bench_result,w.console.toPlainText();result=w._bench_result;assert len(result['x'])>50 and max(result['traces']['out'])>.1;assert all(__import__('math').isfinite(v) for v in result['traces']['out']);(out/'amplifier-ac-result.json').write_text(json.dumps(result,indent=2));checks.append('actual ngspice worker simulates the saved edited amplifier hierarchy after reopening')
# A removal cannot be accepted until the user chooses Disconnect or a replacement.
w.open_symbol_editor(ops.cell(w.project,cid));editor=w._symbol_dialog;s=clone(editor.pad.symbol);s['pins'].pop('sense');s['pin_meta'].pop('sense');s['pin_order'].remove('sense');editor.pad.apply(s);editor.save();review=w._interface_review;assert not review.apply_button.isEnabled();i=next(i for i in range(review.mapping.rowCount()) if review.mapping.item(i,0).text()=='sense');review.mapping.cellWidget(i,1).setCurrentIndex(1);review.prepare();assert review.apply_button.isEnabled(),review.error.text();before=clone(w.project);review.apply();assert editor.saved and 'sense' not in ops.cell(w.project,cid)['ports'];w.undo();assert w.project['cells']==before['cells'];checks.append('used-terminal removal requires explicit Disconnect and can be completely undone')
# A project edit after preparation invalidates Apply without touching the interface.
w.open_symbol_editor(ops.cell(w.project,cid));editor=w._symbol_dialog;s=rename(editor.pad.symbol,'input','input_new');editor.pad.apply(s);editor.save();review=w._interface_review;w.capture_commit(lambda p:p.update(name='Changed after review'),'Edit project name');before=clone(w.project);review.apply();assert 'project changed' in review.error.text().lower() and w.project==before;review.reject();editor.reject();checks.append('stale native review rejects Apply with no partial update')
# Overlapping selections cycle without moving objects; filters affect hit testing.
w.cid=root;w.mode_combo.setCurrentIndex(0);w.refresh(True);original=next(d for d in w.cell['devices'] if d['kind']=='C');duplicate=clone(original);duplicate.update(id=__import__('icstudio.model',fromlist=['uid']).uid(),name='CL_overlap');w.capture_commit(lambda p:ops.cell(p,root)['devices'].append(duplicate),'Overlap selection fixture');canvas=w.schematic;point=QPointF(original['x'],original['y']);canvas.editor_pointer=point;rows=canvas.capture_candidates(point);assert len(rows)>=2;w.select([rows[0]['id']]);canvas.setFocus();QTest.keyClick(canvas,Qt.Key_Tab);assert w.selection==[rows[1]['id']];canvas.capture_filters={'wires'};assert all('points' in o for o in canvas.capture_candidates(point));canvas.capture_filters={'devices','wires','labels'};w.undo();checks.append('Tab cycles overlapping objects and selection filters preserve wiring tool targets')
w.select([did]);w.capture_start('stretch');assert w.capture_active.text()=='Stretch' and w.capture_cancel.isEnabled();w.capture_cancel.click();assert canvas.tool=='select';w.results_dock.hide();w.resize(1100,760);QTest.qWait(70);w.grab().save(str(out/'compact-editor.png'));w.open_symbol_editor(ops.cell(w.project,cid));w._symbol_dialog.resize(1180,780);QTest.qWait(50);w._symbol_dialog.grab().save(str(out/'symbol-editor.png'));w._symbol_dialog.reject();checks.append('visible active command and Cancel remain available in compact workspace')
assert not errors,errors;w.saved_hash=digest(w.project);w.close();(out/'report.json').write_text(json.dumps({'status':'passed','checks':checks,'errors':errors,'qualification':'Native offscreen build-host acceptance. Amplifier layout is a port-link example, not a foundry-verified amplifier.'},indent=2));print(json.dumps({'status':'passed','checks':len(checks)}))
