"""Shipped, offline compatibility information for supported open tool workflows."""
ROWS=[
 ('Xschem','Schematic exchange','Import / export','Direct .sch opening includes standard symbols and public GF180 simulation libraries. Native and compatible projects export declarative device definitions, hierarchy, embedded models and artwork. Reimport reviews edits and restores stable identities, physical views and requirements from matching metadata. Missing custom symbols remain visible placeholders. Tcl netlisting programs and vector buses need an external Xschem workflow.'),
 ('ngspice','Circuit simulation','Included desktop runtime','Native analyses and preserved Xschem control programs, loops, measurements and output files. Each captured analysis is listed with selectable waveforms and exact X/Y checks. The source package can use an installed ngspice. Circuit errors remain visible in the run log.'),
 ('KLayout','Geometry and interchange','Bundled library','GDSII / OASIS hierarchy, geometry operations and generic checks. Open .lyrdb findings with cell/geometry selection. Self-contained .drc scripts run as queued jobs through an installed KLayout executable, retaining input, script, engine and report hashes. Imported geometry does not imply recovered schematic intent or complete macro compatibility.'),
 ('Magic','Layout conversion / extraction','Included physical runtime','Tools / Physical tools setup prepares the included engine on Linux or Windows with WSL 2. Qualified process flows require the matching technology file; standalone conversion can use a custom installation. Reference-flow verification does not qualify arbitrary layouts.'),
 ('Netgen','Netlist comparison','Included physical runtime','Included verification or a custom installation runs extracted-versus-source checks with a matching setup file and device mappings. A pass applies to that executed comparison.'),
 ('OpenVAF','Compiled model support','Included IHP models','The physical runtime includes compiled OSDI libraries for the bundled IHP revision. Custom revisions can use libraries selected in Simulation runtime. Source hashes, binary architecture and runtime availability are checked.'),
 ('IC Design Studio','Local simulations','Built in','Generic teaching solver, native graphical ngspice analyses, parameter/PVT/tolerance cases, finite-difference sensitivity, bounded parameter search, parallel workers, waveform markers and threshold checks. Built-in models do not replace linked PDK models.'),
 ('IC Design Studio','Project and layout editing','Native','Stored manual wires, grid placement, linked views, undo/redo, configurable windows, editable shortcut profiles and reusable cells. Engineering preview; unrestricted signoff and foundry qualification are outside this release.'),
]
