"""Validated design intent shared by synthesis and static timing analysis.

SDC remains an editable input. Structured intent owns only its generated file;
an arbitrary user SDC is never parsed or silently rewritten.
"""
from __future__ import annotations

import math
import re

from .model import clone

IDENT = re.compile(r'[A-Za-z_][A-Za-z0-9_$]*\Z')


def number(value, label, minimum=0, positive=False):
    if type(value) not in (int, float) or not math.isfinite(value) or value < minimum or positive and value == 0:
        raise ValueError(label + ' must be a finite ' + ('positive' if positive else 'nonnegative') + ' number.')
    return value


def validate(value):
    if not isinstance(value, dict) or value.get('version') != 1:
        raise ValueError('Use version 1 digital constraints.')
    clocks = value.get('clocks', [])
    if not isinstance(clocks, list) or not 1 <= len(clocks) <= 32:
        raise ValueError('Define 1–32 clocks.')
    names = set()
    for clock in clocks:
        if not isinstance(clock, dict) or not IDENT.fullmatch(clock.get('name', '')):
            raise ValueError('Use an identifier for each clock name.')
        if clock['name'] in names:
            raise ValueError('Clock names must be unique.')
        names.add(clock['name'])
        if not isinstance(clock.get('port'), str) or not clock['port'].strip():
            raise ValueError('Each clock needs a port expression.')
        number(clock.get('period_ns'), 'Clock period', positive=True)
        number(clock.get('uncertainty_ns', 0), 'Clock uncertainty')
        number(clock.get('transition_ns', 0), 'Clock transition')
    for direction in ('inputs', 'outputs'):
        ports = value.get(direction, [])
        if not isinstance(ports, list) or len(ports) > 256:
            raise ValueError('Use at most 256 I/O constraint groups.')
        for port in ports:
            if not isinstance(port, dict) or port.get('clock') not in names:
                raise ValueError('Each I/O group must reference a defined clock.')
            if not isinstance(port.get('ports'), str) or not port['ports'].strip():
                raise ValueError('Each I/O group needs a port expression.')
            for key in ('min_ns', 'max_ns'):
                val = port.get(key)
                if type(val) not in (float, int) or not math.isfinite(val):
                    raise ValueError('I/O delays must be finite numbers in ns.')
            if port['min_ns'] > port['max_ns']:
                raise ValueError('Minimum I/O delay must not exceed maximum delay.')
    number(value.get('load_pf', 0), 'Output load')
    driver = value.get('driving_cell', '')
    if not isinstance(driver, str) or driver and not IDENT.fullmatch(driver):
        raise ValueError('Use a Liberty cell identifier for the input driver.')
    for key in ('max_transition_ns', 'max_capacitance_pf'):
        if value.get(key) is not None:
            number(value[key], key, positive=True)
    return value


def sdc(value):
    from .engines import tcl_word
    validate(value)
    lines = ['# Generated by IC Design Studio. Time: ns; capacitance: pF.',
             'set_cmd_units -time ns -capacitance pF']
    for clock in value['clocks']:
        name = tcl_word(clock['name'])
        lines.append(f'create_clock -name {name} -period {clock["period_ns"]} [get_ports {tcl_word(clock["port"])}]')
        if clock.get('uncertainty_ns'):
            lines.append(f'set_clock_uncertainty {clock["uncertainty_ns"]} [get_clocks {name}]')
        if clock.get('transition_ns'):
            lines.append(f'set_clock_transition {clock["transition_ns"]} [get_clocks {name}]')
    for direction, key in (('input', 'inputs'), ('output', 'outputs')):
        for group in value.get(key, []):
            for kind in ('min', 'max'):
                lines.append(f'set_{direction}_delay -{kind} {group[kind+"_ns"]} -clock {tcl_word(group["clock"])} [get_ports {tcl_word(group["ports"])}]')
    if value.get('driving_cell'):
        lines.append('set_driving_cell -lib_cell ' + tcl_word(value['driving_cell']) + ' [all_inputs]')
    if value.get('load_pf'):
        lines.append(f'set_load {value["load_pf"]} [all_outputs]')
    for key, command in (('max_transition_ns', 'set_max_transition'), ('max_capacitance_pf', 'set_max_capacitance')):
        if value.get(key) is not None:
            lines.append(f'{command} {value[key]} [current_design]')
    return '\n'.join(lines) + '\n'


def apply(config, value, path='constraints.sdc'):
    """Return a candidate; callers commit it through the document transaction."""
    from .digital import relative_path
    relative_path(path)
    if any(f['path'].casefold()==path.casefold() and f['role']!='constraint' for f in config['files']):
        raise ValueError('The constraint filename belongs to another source. Rename it before generating SDC.')
    out = clone(config)
    out['constraints'] = clone(validate(value))
    out['files'] = [f for f in out['files'] if f['role'] != 'constraint' and f['path'] != path]
    out['files'].append({'path': path, 'role': 'constraint', 'text': sdc(value)})
    return out


def synthesis_settings(config):
    """A conservative single delay budget; full SDC stays with STA/physical tools."""
    explicit = config.get('synthesis', {})
    if not isinstance(explicit, dict) or set(explicit) - {'delay_ns', 'driving_cell', 'load_pf', 'frontend'}:
        raise ValueError('Unknown synthesis option.')
    value = config.get('constraints')
    result = {'frontend': explicit.get('frontend', 'verilog')}
    if result['frontend'] not in ('verilog', 'slang'):
        raise ValueError('Choose the Verilog or slang synthesis frontend.')
    if value:
        validate(value)
        # Only bind to structured timing when its generated SDC is still intact.
        files = [f for f in config['files'] if f['role'] == 'constraint']
        if len(files) != 1 or files[0]['text'] != sdc(value):
            if 'delay_ns' not in explicit:
                raise ValueError('The SDC was edited. Set an explicit synthesis delay budget or regenerate structured constraints.')
        else:
            budgets = []
            for clock in value['clocks']:
                incoming = max([0] + [g['max_ns'] for g in value.get('inputs', []) if g['clock'] == clock['name']])
                outgoing = max([0] + [g['max_ns'] for g in value.get('outputs', []) if g['clock'] == clock['name']])
                budgets.append(clock['period_ns'] - clock.get('uncertainty_ns', 0) - incoming - outgoing)
            result.update(delay_ns=min(budgets), driving_cell=value.get('driving_cell', ''), load_pf=value.get('load_pf', 0))
    result.update(explicit)
    if 'delay_ns' in result:
        number(result['delay_ns'], 'Synthesis delay budget', positive=True)
    if 'load_pf' in result:
        number(result['load_pf'], 'Synthesis output load')
    if result.get('driving_cell') and not IDENT.fullmatch(result['driving_cell']):
        raise ValueError('Invalid synthesis driving cell.')
    return result


def default_intent():
    return {'version': 1, 'clocks': [{'name': 'core_clk', 'port': 'clk', 'period_ns': 10, 'uncertainty_ns': 0.1}],
            'inputs': [{'ports': 'reset', 'clock': 'core_clk', 'min_ns': 0, 'max_ns': 1}],
            'outputs': [{'ports': 'count*', 'clock': 'core_clk', 'min_ns': 0, 'max_ns': 1}],
            'load_pf': 0.01, 'driving_cell': ''}
