"""Compare direct import/export with independent ngspice and optional Xschem.

Run on a desktop with the supplied open-source engines installed. No source
project scripts or startup files are executed; this test uses its own fixture.
"""
import argparse,json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from icstudio.model import clone,save_project,atomic_write
from icstudio.xschem_project import review_schematic,apply_review,export_project
from icstudio.interchange import spice
from icstudio.engines import execute,tcl_word,run_deck


def reference(resistance='8k',width='12u'):
    return f'''* Independently authored common-source reference
VDD vdd 0 1.8
VIN vin 0 DC 0.8 AC 1
XAMP vin vout vdd 0 gain resistance={resistance} width={width}
CL vout 0 1p
.subckt gain in out vdd vss resistance=10k width=10u
RD vdd out {{resistance}}
M1 out in vss vss nch w={{width}} l=1u
.ends gain
.model nch nmos (level=1 vto=0.45 kp=100u lambda=0.02)
.ac dec 20 10 10meg
.end
'''


def run_case(p,deck,out,ngspice):
    out.mkdir(parents=True,exist_ok=True);file=out/'input.cir';atomic_write(file,deck);result=run_deck(p,p['top'],{'type':'deck','deck':str(file)},ngspice,out);atomic_write(out/'result.json',json.dumps(result,indent=2));return result


def compare(a,b):
    if len(a['x'])!=len(b['x']):raise AssertionError('Different sample counts')
    if any(abs(x-y)>1e-9*max(1,abs(x)) for x,y in zip(a['x'],b['x'])):raise AssertionError('Different frequency grids')
    errors=[abs(x-y)/max(abs(x),1e-12) for x,y in zip(a['traces']['vout'],b['traces']['vout'])]
    maximum=max(errors);assert maximum<1e-7,maximum
    pa=a.get('phase',{}).get('vout',[]);pb=b.get('phase',{}).get('vout',[])
    phase_error=max((abs((x-y+180)%360-180) for x,y in zip(pa,pb)),default=0.);assert phase_error<1e-6,phase_error
    return {'samples':len(errors),'maximum_relative_magnitude_error':maximum,'maximum_phase_error_degrees':phase_error}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,required=True);parser.add_argument('--ngspice',required=True);parser.add_argument('--xschem');parser.add_argument('--xschem-share',type=Path);args=parser.parse_args();out=args.output.resolve()
    if out.exists() and any(out.iterdir()):raise ValueError('Choose an empty verification directory.')
    out.mkdir(parents=True);import shutil;shutil.copytree(ROOT/'examples/xschem-amplifier',out/'original');top=out/'original/amplifier.sch';record=review_schematic(top);assert not record['errors'],record['errors'];p=apply_review(record);checks=[];attempts=[]
    for name,resistance,width in [('original','8k','12u'),('edited','6k','16u')]:
        q=clone(p);root=next(c for c in q['cells'] if c['id']==q['top']);inst=next(d for d in root['devices'] if d['kind']=='X');inst['parameters'].update(resistance=resistance,width=width);export=out/name/'export';export_project(q,export);r=apply_review(review_schematic(export/'amplifier.sch'));save_project(r,out/name/'imported.icproj')
        baseline=run_case(q,reference(resistance,width),out/name/'reference',args.ngspice);native=run_case(q,spice(q,settings=q['analysis']),out/name/'native',args.ngspice);roundtrip=run_case(r,spice(r,settings=r['analysis']),out/name/'roundtrip',args.ngspice)
        checks.append({'case':name,'native_against_reference':compare(baseline,native),'roundtrip_against_reference':compare(baseline,roundtrip)})
        if args.xschem:
            run=out/name/'xschem';run.mkdir();(run/'profile').mkdir();rc=run/'xschemrc';rc.write_text(('set XSCHEM_SHAREDIR '+tcl_word(args.xschem_share.resolve())+'\n' if args.xschem_share else '')+'set XSCHEM_LIBRARY_PATH '+tcl_word(export)+'\nset USER_CONF_DIR '+tcl_word(run/'profile')+'\nset XSCHEM_TMP_DIR '+tcl_word(run)+'\nset undo_type disk\n')
            try:
                startup=['--preinit','set XSCHEM_SHAREDIR '+tcl_word(args.xschem_share.resolve())] if args.xschem_share else []
                log=execute([args.xschem,'-x','-r','-q','-n','-s',*startup,'--rcfile',rc,'-o',run,export/'amplifier.sch'],args.xschem_share.resolve() if args.xschem_share else export,timeout=30);atomic_write(run/'netlisting.log',log)
                deck=(run/'amplifier.spice').read_text();assert deck.strip() and not re.search('unable to open|FATAL|not found|SKIPPING|Error:|failed',log,re.I),log
                # Relative includes generated by Xschem resolve in the export folder.
                deck=re.sub(r'(?im)(\.include|\.inc)\s+("[^"]+"|\S+)',lambda m:m[1]+' '+tcl_word(export/m[2].strip('"')),deck)
                actual=run_case(q,deck,run/'simulation',args.ngspice);checks[-1]['xschem_against_reference']=compare(baseline,actual);attempts.append({'case':name,'status':'passed'})
            except (RuntimeError,OSError,AssertionError,ValueError) as exc:attempts.append({'case':name,'status':'failed','reason':str(exc)})
    report={'status':'passed' if not any(a['status']=='failed' for a in attempts) else 'partial','ngspice':args.ngspice,'checks':checks,'xschem':attempts or [{'status':'not requested'}],'scope':'Independent reference and imported/exported amplitude and phase using the same ngspice engine and illustrative level-1 model; no PDK qualification.'};atomic_write(out/'report.json',json.dumps(report,indent=2));print(json.dumps(report,indent=2));return 0 if report['status']=='passed' else 2


if __name__=='__main__':raise SystemExit(main())
